id = "abysswalker-theme"
name = "Abysswalker"
description = "A minimalist dark theme. Designed for deep focus."
version = "0.1.0"
schema_version = 1
authors = ["Andrii Stavskyi <an.stawski@outlook.com>"]
repository = "https://github.com/stkossman/abysswalker-zed"
